import argparse
import os
import re
from pathlib import Path
from collections import defaultdict

FILE_HEADER_RE = re.compile(r"^\s*##\s+(.+?)\s*$")
ITEM_RE = re.compile(r"^\s*-\s*Line\s+(\d+):\s+\*\*(.+?)\*\*\s+→\s+`(.*?)`\s*$")

DEFAULT_KEYWORDS = []  # empty means include all (TODO/FIXME/mock/hardcode/...)


def parse_report_md(path: Path, keywords: list[str] | None = None):
    """Parse a Todo Scanner style report.md into structured tasks.

    Expected item lines look like:
      - Line 42: **TODO** → `// TODO: 从配置文件读取回测参数`
    under file sections like:
      ## ./path/to/file.ts
    """
    tasks_by_file: dict[str, list[tuple[int, str, str]]] = defaultdict(list)
    current_file: str | None = None

    if keywords:
        keyset = {k.lower() for k in keywords}
    else:
        keyset = None

    for raw in path.read_text(encoding="utf-8").splitlines():
        m_file = FILE_HEADER_RE.match(raw)
        if m_file:
            current_file = m_file.group(1).strip()
            continue

        m_item = ITEM_RE.match(raw)
        if m_item and current_file:
            line_no = int(m_item.group(1))
            kw = m_item.group(2).strip()
            content = m_item.group(3).strip()

            if keyset is None or kw.lower() in keyset:
                tasks_by_file[current_file].append((line_no, kw, content))

    # de-duplicate tasks (same file, line, kw, content)
    for f, items in list(tasks_by_file.items()):
        seen = set()
        uniq = []
        for it in items:
            if it not in seen:
                uniq.append(it)
                seen.add(it)
        # sort by line number
        tasks_by_file[f] = sorted(uniq, key=lambda t: t[0])

    return tasks_by_file


def make_vscode_link(root: Path, file_path: str, line_no: int) -> str:
    # Build an absolute path for vscode://file links
    p = Path(file_path)
    if not p.is_absolute():
        p = (root / p).resolve()
    return f"vscode://file/{p}:{line_no}"


def write_checklist_md(tasks_by_file: dict[str, list[tuple[int, str, str]]], out_path: Path,
                        root: Path, vscode_links: bool):
    lines: list[str] = ["# 开发修复清单（来自 report.md）", ""]

    if not tasks_by_file:
        lines.append("✅ 未在 report.md 中发现可解析的待办项。")
        out_path.write_text("\n".join(lines), encoding="utf-8")
        return

    for file_path, items in tasks_by_file.items():
        if not items:
            continue
        lines.append(f"## {file_path}")
        for line_no, kw, content in items:
            if vscode_links:
                link = make_vscode_link(root, file_path, line_no)
                lines.append(f"- [ ] [{file_path}:{line_no}]({link}) — **{kw}** — {content}")
            else:
                lines.append(f"- [ ] `{file_path}:{line_no}` — **{kw}** — {content}")
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")


def main():
    ap = argparse.ArgumentParser(description="Convert Todo Scanner report.md into an actionable checklist for Cursor/IDE")
    ap.add_argument("report", help="Path to report.md generated by the scanner")
    ap.add_argument("-o", "--output", default="todo_checklist.md", help="Output markdown file (default: todo_checklist.md)")
    ap.add_argument("-k", "--keywords", nargs="*", default=DEFAULT_KEYWORDS,
                    help="Only include these keyword types (e.g. TODO FIXME mock hardcode). Empty=include all")
    ap.add_argument("--vscode-links", action="store_true", help="Emit vscode://file links for one-click navigation")
    ap.add_argument("--root", default=".", help="Project root used to resolve relative paths for links (default: .)")

    args = ap.parse_args()

    report_path = Path(args.report)
    if not report_path.exists():
        raise SystemExit(f"❌ report not found: {report_path}")

    tasks = parse_report_md(report_path, args.keywords if args.keywords else None)
    write_checklist_md(tasks, Path(args.output), Path(args.root).resolve(), args.vscode_links)
    print(f"✅ 已生成清单: {args.output}")


if __name__ == "__main__":
    main()
